### PR TITLE
feat : Auth routes completed for email/password

### PR DESCRIPTION
**Pull request by kanha638**
Issue Attached : #5 
Included : 
1. Created `/api/v1/sign-up` route.
2. Created `/api/v1/sign-in` route.
3. Both routes demo can be seen over `http://127.0.0.1:8000/docs`.Please test it from over there  

Note : Changed `requirements.txt` so make sure to install the new packages under your virtual environment using `pip3 install -r requirements.txt` before running the app

### CODE REVIEW

**Comment by kanha638** [comment]
> Is it okay to expose secret key and encryption algorithm etc.?

Yes as this is for development purpose and can be taken from environment when on production or deployment.

**Comment by kanha638** [comment]
@kamalkish0r Pushed one more change resolving your query.

**Review by kamalkish0r — APPROVED** [review]
Looks fine

**Review by kanha638 — COMMENTED** [review]
Rechecked

**Pull request merged**
